<?php /* * Download the file given at filename, in the directory that contains the csv 's
   * generated by the application. Trying to provide a string to select another
   * directory will fail.
   */
  function downloadFile($filename) {
    // Check file exists and then download.
    if (file_exists($filename)) {
      ob_clean(); // Clean the buffer, ensures no HTML in file
      // Set all the headers
      header('Pragma: public ');
      header('Expires: 0 ');
      header('Cache-Control: must-revalidate, post-check=0, pre-check=0 ');
      header('Content-Description: File Transfer ');
      header('Content-Type: application/octet-stream ');
      header("Content-Disposition: attachment; filename=".basename($filename));
      header('Content-Transfer-Encoding: binary ');
      header('Content-Length: ' . filesize($filename));
      header('Connection: close ');
      // Read the file to the buffer
      readfile($filename);
      // Remove the file
      unlink($filename);
    }
  }
  
  // Ensure a filename provided
  if (!(isset($_REQUEST['file ']))) die ("Need a file request");
  
  // Get the path for the file.
  $baseDir =  "/var/tmp/web/";
  $path = realpath($baseDir . $_REQUEST['file ']);
  
  // Ensure no one is trying to steal files, then download.
  if (strpos($path, $baseDir) !== 0) die ("Stop trying to steal files!");
  else if (file_exists($path)) downloadFile($path);
  else die ("No file by that name.");
?>