//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAustralian_Postcode_Validation")]
    public interface IAustralian_Postcode_Validation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAustralian_Postcode_Validation/DoWork", ReplyAction="http://tempuri.org/IAustralian_Postcode_Validation/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAustralian_Postcode_Validation/PostcodeValidation", ReplyAction="http://tempuri.org/IAustralian_Postcode_Validation/PostcodeValidationResponse")]
        bool PostcodeValidation(int postcode, string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAustralian_Postcode_Validation/SaveInfo", ReplyAction="http://tempuri.org/IAustralian_Postcode_Validation/SaveInfoResponse")]
        bool SaveInfo(string firstName, string lastName, System.DateTime dateOfBirth, string email, string streetAddress, string suburb, string state, int postcode, int positionNumber, string positionTitle, string positionDescription, string companyName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAustralian_Postcode_ValidationChannel : WebApplication1.ServiceReference1.IAustralian_Postcode_Validation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Australian_Postcode_ValidationClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IAustralian_Postcode_Validation>, WebApplication1.ServiceReference1.IAustralian_Postcode_Validation {
        
        public Australian_Postcode_ValidationClient() {
        }
        
        public Australian_Postcode_ValidationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Australian_Postcode_ValidationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Australian_Postcode_ValidationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Australian_Postcode_ValidationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public bool PostcodeValidation(int postcode, string state) {
            return base.Channel.PostcodeValidation(postcode, state);
        }
        
        public bool SaveInfo(string firstName, string lastName, System.DateTime dateOfBirth, string email, string streetAddress, string suburb, string state, int postcode, int positionNumber, string positionTitle, string positionDescription, string companyName) {
            return base.Channel.SaveInfo(firstName, lastName, dateOfBirth, email, streetAddress, suburb, state, postcode, positionNumber, positionTitle, positionDescription, companyName);
        }
    }
}
