//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IADODatabaseService")]
    public interface IADODatabaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADODatabaseService/DoWork", ReplyAction="http://tempuri.org/IADODatabaseService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADODatabaseService/PatientRegistration", ReplyAction="http://tempuri.org/IADODatabaseService/PatientRegistrationResponse")]
        bool PatientRegistration(string healthInsuranceNO, string fname, string lname, int pnumber, string address, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IADODatabaseServiceChannel : WebApplication1.ServiceReference1.IADODatabaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ADODatabaseServiceClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IADODatabaseService>, WebApplication1.ServiceReference1.IADODatabaseService {
        
        public ADODatabaseServiceClient() {
        }
        
        public ADODatabaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ADODatabaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADODatabaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADODatabaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public bool PatientRegistration(string healthInsuranceNO, string fname, string lname, int pnumber, string address, string email) {
            return base.Channel.PatientRegistration(healthInsuranceNO, fname, lname, pnumber, address, email);
        }
    }
}
