/*

Oracle Client Version : 10.2.0.5.0

Source Server         : 127.0.0.1
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : USER_HP_FULL

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2012-07-21 17:21:54
*/


-- ----------------------------
-- Table structure for COUNTRY
-- ----------------------------

CREATE TABLE COUNTRY (
Code VARCHAR2(255 CHAR) NULL ,
CountryName VARCHAR2(255 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

-- ----------------------------
-- Records of COUNTRY
-- ----------------------------
INSERT INTO COUNTRY VALUES ('AFG', 'Afghanistan');
INSERT INTO COUNTRY VALUES ('AHO', 'Netherland Antilles');
INSERT INTO COUNTRY VALUES ('ALG', 'Algeria');
INSERT INTO COUNTRY VALUES ('ANZ', 'Australasia (until 1920)');
INSERT INTO COUNTRY VALUES ('ARG', 'Argentina');
INSERT INTO COUNTRY VALUES ('ARM', 'Armenia');
INSERT INTO COUNTRY VALUES ('AUS', 'Australia');
INSERT INTO COUNTRY VALUES ('AUT', 'Austria');
INSERT INTO COUNTRY VALUES ('AZE', 'Azerbaijan');
INSERT INTO COUNTRY VALUES ('BAH', 'Bahamas');
INSERT INTO COUNTRY VALUES ('BAR', 'Barbados');
INSERT INTO COUNTRY VALUES ('BDI', 'Burundi');
INSERT INTO COUNTRY VALUES ('BEL', 'Belgium');
INSERT INTO COUNTRY VALUES ('BER', 'Bermuda');
INSERT INTO COUNTRY VALUES ('BIN', 'British India');
INSERT INTO COUNTRY VALUES ('BLR', 'Belarus');
INSERT INTO COUNTRY VALUES ('BOH', 'Bohemia');
INSERT INTO COUNTRY VALUES ('BRA', 'Brazil');
INSERT INTO COUNTRY VALUES ('BRN', 'Bahrain');
INSERT INTO COUNTRY VALUES ('BUL', 'Bulgaria');
INSERT INTO COUNTRY VALUES ('BUR', 'Burkina Faso');
INSERT INTO COUNTRY VALUES ('BWI', 'British West Indies');
INSERT INTO COUNTRY VALUES ('CAN', 'Canada');
INSERT INTO COUNTRY VALUES ('CHI', 'Chile');
INSERT INTO COUNTRY VALUES ('CHN', 'China');
INSERT INTO COUNTRY VALUES ('CIV', 'Ivory Coast');
INSERT INTO COUNTRY VALUES ('CMR', 'Cameroon');
INSERT INTO COUNTRY VALUES ('COL', 'Colombia');
INSERT INTO COUNTRY VALUES ('CRC', 'Costa Rica');
INSERT INTO COUNTRY VALUES ('CRO', 'Croatia');
INSERT INTO COUNTRY VALUES ('CUB', 'Cuba');
INSERT INTO COUNTRY VALUES ('CZE', 'Czechoslovakia (until 1992)');
INSERT INTO COUNTRY VALUES ('CZR', 'Czech Rep.');
INSERT INTO COUNTRY VALUES ('DEN', 'Denmark');
INSERT INTO COUNTRY VALUES ('DEU', 'Germany (until 1912)');
INSERT INTO COUNTRY VALUES ('DJI', 'Djibouti');
INSERT INTO COUNTRY VALUES ('DOM', 'Dominican Rep.');
INSERT INTO COUNTRY VALUES ('ECU', 'Ecuador');
INSERT INTO COUNTRY VALUES ('EGY', 'Egypt');
INSERT INTO COUNTRY VALUES ('ERI', 'Eritrea');
INSERT INTO COUNTRY VALUES ('ESP', 'Spain');
INSERT INTO COUNTRY VALUES ('EST', 'Estonia');
INSERT INTO COUNTRY VALUES ('ETH', 'Ethiopia');
INSERT INTO COUNTRY VALUES ('FIN', 'Finland');
INSERT INTO COUNTRY VALUES ('FRA', 'France');
INSERT INTO COUNTRY VALUES ('FRG', 'West Germany');
INSERT INTO COUNTRY VALUES ('GBR', 'United Kingdom');
INSERT INTO COUNTRY VALUES ('GDR', 'East Germany');
INSERT INTO COUNTRY VALUES ('GEO', 'Georgia');
INSERT INTO COUNTRY VALUES ('GER', 'Germany');
INSERT INTO COUNTRY VALUES ('GHA', 'Ghana');
INSERT INTO COUNTRY VALUES ('GRE', 'Greece');
INSERT INTO COUNTRY VALUES ('GUY', 'Guyana');
INSERT INTO COUNTRY VALUES ('HAI', 'Haiti');
INSERT INTO COUNTRY VALUES ('HKG', 'Hong Kong');
INSERT INTO COUNTRY VALUES ('HUN', 'Hungary');
INSERT INTO COUNTRY VALUES ('ICE', 'Iceland');
INSERT INTO COUNTRY VALUES ('INA', 'Indonesia');
INSERT INTO COUNTRY VALUES ('IND', 'India');
INSERT INTO COUNTRY VALUES ('INT', 'International Team');
INSERT INTO COUNTRY VALUES ('IRI', 'Iran');
INSERT INTO COUNTRY VALUES ('IRL', 'Ireland');
INSERT INTO COUNTRY VALUES ('IRQ', 'Iraq');
INSERT INTO COUNTRY VALUES ('ISR', 'Israel');
INSERT INTO COUNTRY VALUES ('ISV', 'Virgin Islands US');
INSERT INTO COUNTRY VALUES ('ITA', 'Italy');
INSERT INTO COUNTRY VALUES ('JAM', 'Jamaica');
INSERT INTO COUNTRY VALUES ('JPN', 'Japan');
INSERT INTO COUNTRY VALUES ('KAZ', 'Kazakhstan');
INSERT INTO COUNTRY VALUES ('KEN', 'Kenya');
INSERT INTO COUNTRY VALUES ('KGZ', 'Kyrgyzstan');
INSERT INTO COUNTRY VALUES ('KIT', 'Italy (until 1946)');
INSERT INTO COUNTRY VALUES ('KOR', 'South Korea');
INSERT INTO COUNTRY VALUES ('KSA', 'Saudi Arabia');
INSERT INTO COUNTRY VALUES ('KUW', 'Kuwait');
INSERT INTO COUNTRY VALUES ('LAT', 'Latvia');
INSERT INTO COUNTRY VALUES ('LIB', 'Lebanon');
INSERT INTO COUNTRY VALUES ('LIE', 'Liechtenstein');
INSERT INTO COUNTRY VALUES ('LTU', 'Lithuania');
INSERT INTO COUNTRY VALUES ('LUX', 'Luxembourg');
INSERT INTO COUNTRY VALUES ('MAR', 'Morocco');
INSERT INTO COUNTRY VALUES ('MAS', 'Malaysia');
INSERT INTO COUNTRY VALUES ('MDA', 'Moldova');
INSERT INTO COUNTRY VALUES ('MEX', 'Mexico');
INSERT INTO COUNTRY VALUES ('MGL', 'Mongolia');
INSERT INTO COUNTRY VALUES ('MKD', 'Macedonia');
INSERT INTO COUNTRY VALUES ('MON', 'Monaco');
INSERT INTO COUNTRY VALUES ('MOZ', 'Mozambique');
INSERT INTO COUNTRY VALUES ('MRI', 'Mauritius');
INSERT INTO COUNTRY VALUES ('NAM', 'Namibia');
INSERT INTO COUNTRY VALUES ('NED', 'Netherlands');
INSERT INTO COUNTRY VALUES ('NGR', 'Nigeria');
INSERT INTO COUNTRY VALUES ('NIG', 'Niger');
INSERT INTO COUNTRY VALUES ('NOR', 'Norway');
INSERT INTO COUNTRY VALUES ('NZL', 'New Zealand');
INSERT INTO COUNTRY VALUES ('PAK', 'Pakistan');
INSERT INTO COUNTRY VALUES ('PAN', 'Panama');
INSERT INTO COUNTRY VALUES ('PAR', 'Paraguay');
INSERT INTO COUNTRY VALUES ('PER', 'Peru');
INSERT INTO COUNTRY VALUES ('PHI', 'Philippines');
INSERT INTO COUNTRY VALUES ('POL', 'Poland');
INSERT INTO COUNTRY VALUES ('POR', 'Portugal');
INSERT INTO COUNTRY VALUES ('PRK', 'North Korea');
INSERT INTO COUNTRY VALUES ('PUR', 'Puerto Rico');
INSERT INTO COUNTRY VALUES ('QAT', 'Qatar');
INSERT INTO COUNTRY VALUES ('ROM', 'Romania');
INSERT INTO COUNTRY VALUES ('RSA', 'South Africa');
INSERT INTO COUNTRY VALUES ('RUS', 'Russia');
INSERT INTO COUNTRY VALUES ('SAF', 'South Africa (until 1960)');
INSERT INTO COUNTRY VALUES ('SEN', 'Senegal');
INSERT INTO COUNTRY VALUES ('SIN', 'Singapore');
INSERT INTO COUNTRY VALUES ('SLO', 'Slovenia');
INSERT INTO COUNTRY VALUES ('SRB', 'Serbia');
INSERT INTO COUNTRY VALUES ('SRI', 'Sri Lanka');
INSERT INTO COUNTRY VALUES ('SUD', 'Sudan');
INSERT INTO COUNTRY VALUES ('SUI', 'Switzerland');
INSERT INTO COUNTRY VALUES ('SUR', 'Suriname');
INSERT INTO COUNTRY VALUES ('SVK', 'Slovak Rep.');
INSERT INTO COUNTRY VALUES ('SWE', 'Sweden');
INSERT INTO COUNTRY VALUES ('SYR', 'Syria');
INSERT INTO COUNTRY VALUES ('TAN', 'Tanzania');
INSERT INTO COUNTRY VALUES ('TGA', 'Tonga');
INSERT INTO COUNTRY VALUES ('THA', 'Thailand');
INSERT INTO COUNTRY VALUES ('TJK', 'Tajikistan');
INSERT INTO COUNTRY VALUES ('TOG', 'Togo');
INSERT INTO COUNTRY VALUES ('TPE', 'Taiwan');
INSERT INTO COUNTRY VALUES ('TRI', 'Trinidad Tobago');
INSERT INTO COUNTRY VALUES ('TUN', 'Tunisia');
INSERT INTO COUNTRY VALUES ('TUR', 'Turkey');
INSERT INTO COUNTRY VALUES ('UAE', 'United Arab Emirates');
INSERT INTO COUNTRY VALUES ('UGA', 'Uganda');
INSERT INTO COUNTRY VALUES ('UKR', 'Ukraine');
INSERT INTO COUNTRY VALUES ('URS', 'Soviet Union');
INSERT INTO COUNTRY VALUES ('URU', 'Uruguay');
INSERT INTO COUNTRY VALUES ('USA', 'United States');
INSERT INTO COUNTRY VALUES ('UZB', 'Uzbekistan');
INSERT INTO COUNTRY VALUES ('VEN', 'Venezuela');
INSERT INTO COUNTRY VALUES ('VIE', 'Vietnam');
INSERT INTO COUNTRY VALUES ('YUF', 'Yugoslav Federation');
INSERT INTO COUNTRY VALUES ('YUG', 'Yugoslavia (until 1988)');
INSERT INTO COUNTRY VALUES ('ZAM', 'Zambia');
INSERT INTO COUNTRY VALUES ('ZIM', 'Zimbabwe');
