//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IPeople_and_Job_Information_Management")]
    public interface IPeople_and_Job_Information_Management {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeople_and_Job_Information_Management/DoWork", ReplyAction="http://tempuri.org/IPeople_and_Job_Information_Management/DoWorkResponse")]
        void DoWork();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPeople_and_Job_Information_ManagementChannel : WebApplication1.ServiceReference2.IPeople_and_Job_Information_Management, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class People_and_Job_Information_ManagementClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference2.IPeople_and_Job_Information_Management>, WebApplication1.ServiceReference2.IPeople_and_Job_Information_Management {
        
        public People_and_Job_Information_ManagementClient() {
        }
        
        public People_and_Job_Information_ManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public People_and_Job_Information_ManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public People_and_Job_Information_ManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public People_and_Job_Information_ManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
    }
}
